version: '3.8'

services:
  app:
    container_name: sreach_model
    build: ..
    command: poetry run gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.app:app --bind 127.0.0.1:8000
    ports:
      - "8000:8000"
    volumes:
      - ..:/code 
    networks:
      - backend

networks:
  backend:
    driver: bridge